install:
	whoami
	python3 -m venv venv
	. ./venv/bin/activate && pip install -r requirements.txt
	pip install flask
	pip install flask_compress
	pip install requests
	pip install request
	pip install flask-cors

start:
	python3 server.py
