install:
	whoami
	python3 -m venv venv
	. ./venv/bin/activate && pip install -r requirements.txt
	pip3 install flask
	pip3 install flask_compress
	pip3 install requests
	pip3 install request
	pip3 install flask-cors

start:
	python3 server.py
